# -*- coding: utf-8 -*-
"""BFSgraphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiDVU5vHKfvONfCMMNJEp4C_LHX_3W-y
"""

def bfs(graph, start):
    visited = set()
    queue = [start]
    visited.add(start)
    while queue:
        node = queue.pop(0)
        print(node, end=' ')
        for neighbor in graph[node]:
            if neighbor not in visited:
                queue.append(neighbor)
                visited.add(neighbor)

graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'F'],
    'C': ['A', 'F'],
    'D': ['B', 'E'],
    'E': ['D', 'C', 'F'],
    'F': ['B', 'C', 'E']
}

bfs(graph, 'A')