# -*- coding: utf-8 -*-
"""FloydWarshall.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_Djos_M3uemD6u7Ys2wG3S_6RTLimZK
"""

def floyd_warshall(graph):
    dist = {n1: {n2: float('inf') for n2 in graph} for n1 in graph}
    for n in graph:
        dist[n][n] = 0
        for nbr, w in graph[n].items():
            dist[n][nbr] = w

    for k in graph:
        for i in graph:
            for j in graph:
                dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])

    return dist

graph = {
    'A': {'A': 0, 'B': 3, 'C': 8},
    'B': {'A': float('inf'), 'B': 0, 'C': float('inf')},
    'C': {'A': float('inf'), 'B': 1, 'C': 0}
}

print(floyd_warshall(graph))